version: '3.8'
services:
  doc_processor_api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./save_documents:/app/save_documents
      - ./documentos_metadados.json:/app/documentos_metadados.json
      - ./indice_invertido.json:/app/indice_invertido.json
    environment:
      - PYTHONUNBUFFERED=1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}





